### ISSUE TITLE
not all guitarix fx plugins appear

### ISSUE THREAD

**Issue by autumncheney** [DISTRHO/Ildaeil#2]
on ubuntu studio 20.10, quite a few of my guitarix plugins are missing from ildaeil-fx. mostly the distortions

tested in radium 6.9.96

**Comment by falkTX** [comment]
Likely they are mono plugins, those are unsupported in this host.

**Comment by autumncheney** [comment]
ah ok

suggestion: perhaps you could try running two instances of the mono plugin in parallel, and just link each control to the two instances?

**Comment by falkTX** [comment]
Done in 5347c6eefc9f4840297ede3929b1978ab1440720
Some mono plugins will force the stereo signal to mono, some can run as 2 instances, it depends on the features the plugin requires to run (carla will only run 2 instances for the more simple plugins).
