### ISSUE TITLE
Plugins are not found

### ISSUE THREAD

**Issue by tobiasBora** [DISTRHO/Ildaeil#4]
I tried to install Ildaeil, but when I run it (inside Bespoke), I get an error "There are no  LV2 audio plugins on this sytem".

![image](https://user-images.githubusercontent.com/2164118/141492593-382de2b6-8909-4f01-ae68-942f674e46b5.png)

But I do have many lv2 plugins, and they are detected in Carla (ok, in carla I need to configure the paths), Ardour, lv2ls…:
```
$ lv2ls 
http://arcticanaudio.com/plugins/thefunction
http://arcticanaudio.com/plugins/thepilgrim
http://au.tomatl.org/essp
http://calf.sourceforge.net/plugins/Analyzer
http://calf.sourceforge.net/plugins/BassEnhancer
http://calf.sourceforge.net/plugins/CompensationDelay
http://calf.sourceforge.net/plugins/Compressor
http://calf.sourceforge.net/plugins/Crusher
[...]
```
In which path is Ildaeil searching for the plugins? Is it looking for the environment variable `$LV2_PATH`?
```
$ echo $LV2_PATH
~/.nix-profile/lib/lv2/:~/.lv2:/nix/var/nix/profiles/default/lib/lv2:/var/run/current-system/sw/lib/lv2
```

**EDIT**

It seems plugins are found if they are in `~/.lv2`. However, it would be better to also look for the `$LV2_PATH` which seems to be more standard.

**Comment by falkTX** [comment]
Yeah this is a bug, it should be using LV2_PATH but instead it uses an internal var.
Try changing the line https://github.com/DISTRHO/Ildaeil/blob/main/plugins/Common/IldaeilUI.cpp#L498 and replacing nullptr with `getenv("LV2_PATH")`.
Let me know if that improves things, thanks.

**Comment by tobiasBora** [comment]
This works perfectly!
