### ISSUE TITLE
Why SFZero and not sfizz?

### ISSUE THREAD

**Issue by unfa** [DISTRHO/Ildaeil#5]
SFZero seems to be an old project with no updates for half a decade, while sfizz is constantly updated and improved.

sfizz is already used internally by a plug-ins called DROPS to play back samples, so it is very possible to use it's engine in another plug-in.

Why choose SFZero over sfizz?

**Comment by falkTX** [comment]
sfizz is quite complex, and also new. when making carla drop linuxsampler (for license reasons mostly) sfizz was not up to the state where it is now.
also I still want Carla code to remain C++98 compatible, while sfizz requires C++11. it just complicates the build process much more compared to something simple like sfzero.
in the future carla could make use of sfizz if available (as external library), and fallback to sfzero.

anyway, this is not related to ildaeil at all. ildaeil does not load sfz files at all..
