### ISSUE TITLE
Parts of GUI missing on Linux + VST3

### ISSUE THREAD

**Issue by fractalf** [DISTRHO/Ildaeil#6]
This was in Bitwig 4.1.6 on Linux Mint 20.3. Just tried some synths I use that already have LV2 plugins installed

![image](https://user-images.githubusercontent.com/5707457/155130705-d7f8d6ea-0862-416d-94d0-1e5bb77087f9.png)

![image](https://user-images.githubusercontent.com/5707457/155130649-e764244e-be63-4a07-ae03-2ac49b913d66.png)

**Comment by falkTX** [comment]
Typically a plugin's problem.
But all of those on your list have non-LV2 versions, so it does not really matter much.

**Comment by fractalf** [comment]
Yes, this is true, just though I'd report. I'm trying to get x42 stuff working now... How to have Ildaeil look into `~/.lv2` ?

**Comment by falkTX** [comment]
you shouldnt have to do anything for LV2, it will use LV2_PATH env var if set, but it has sane defaults if unset.
but the synth version will only show synths, fx will only show fxs etc.

**Comment by fractalf** [comment]
Right ofc, sorry my bad.

So, what about this one? This should display more of the GUI, kind of simular to the synths

My test:
![image](https://user-images.githubusercontent.com/5707457/155134445-5ffc5ece-802f-4f00-883d-8f4907c48664.png)

Original:
![image](https://user-images.githubusercontent.com/5707457/155134839-76995259-1142-4ea8-963c-173236f4980c.png)

**Comment by falkTX** [comment]
Right, yes, this is an odd one. We can see the outline of the top bar, so Ildaeil doesnt resize its internal window properly.
Does it happen with other hosts in your system too?

Are you using the VST2 or VST3? I am guessing this only happens with VST3, not VST2

**Comment by fractalf** [comment]
I only have Bitwig, no other hosts.
Yea this is the VST3 one. 

Hang on, let me check VST2...

..Oh yea, working perfectly! :) 

This is so freaking amazing, now I can finally use some of the x42 stuff in Bitwig.

You are an audio **hero**, thank you very much :)


![image](https://user-images.githubusercontent.com/5707457/155136318-c1371bd0-09a2-4548-ba22-4ae31d9103d2.png)

**Comment by falkTX** [comment]
Ok, the VST3 support is experimental, so I kinda expected this.
Will be fixed in a future release, for now good to know VST2 still works fine.
Will update the ticket title

**Comment by mikobuntu** [comment]
Confirming the VST3 behaviour on Renoise & Reaper too , but it works perfectly in Tracktion_Waveform_12.0.46 ( beta ) , so this issue might be how the host DAW implements VST3 ?

**Comment by tank-trax** [comment]
this is an issue I have seen with a few VST3 plugins across various hosts

**Comment by falkTX** [comment]
This should be fixed in latest builds, or building from source with latest git.
Confirmation would be very welcome, I am hoping to tag new release tomorrow. Thanks!

**Comment by fractalf** [comment]
> This should be fixed in latest builds... 

I can test this an confirm, but couldn't see the latest builds (only 1.0 from feb)

**Comment by falkTX** [comment]
> couldn't see the latest builds (only 1.0 from feb)

right, I found other issues with the vst3 so I had to postpone the release.

thanks for confirming anyhow, appreciated. closing ticket now.

**Comment by fractalf** [comment]
just to avoid any missunderstanding, I meant i **could** test it, but need the builds :) when done, I will test and then i can confirm

**Comment by fractalf** [comment]
No sorry, no worry m8, I wasn't clear enough.

Tested today and working fine with vst3 in Bitwig 4.1.6 on Linux Mint 20.3!

Thanks a lot for all your effort!
