### ISSUE TITLE
CLAP support

### ISSUE THREAD

**Issue by tank-trax** [DISTRHO/Ildaeil#8]
do you have any intention of adding support for CLAP plugins?

**Comment by falkTX** [comment]
That would need to go into Carla first.
But very little interest on that at the moment, the spec is not even finalized yet.

**Comment by falkTX** [comment]
FYI latest builds (from actions tab) have Ildaeil working as a CLAP plugin.
This will be part of the next release.

Hosting CLAP plugins will come eventually, but not for the next release.

**Comment by falkTX** [comment]
CLAP hosting is in, together with all the other formats.
If using standalone or system-carla, it requires (yet to be released) Carla 2.5.5 that allows automatic plugin scanning, or latest git.

<img width="647" alt="image" src="https://github.com/DISTRHO/Ildaeil/assets/1334853/b45e6c70-d766-4788-b035-38b66af197f9">
