### ISSUE TITLE
Geonkick not showing in list

### ISSUE THREAD

**Issue by fractalf** [DISTRHO/Ildaeil#9]
Did anyone get Geonkick LV2 working? It's not showing in the list here, which is strange, cause lots of other synths show/work.

* https://github.com/free-sm/geonkick
* https://kx.studio/Repositories:Plugins#geonkick

I can get Geonkick working fine as a standalone, but Ildaeil doesn't seem to find it..

So I guess what I'm asking is if this is a problem with Ildaeil or Geonkick..

I'm using the Ildaeil VST2 version in Bitwig 4.1.6 on Linux Mint 20.3

![image](https://user-images.githubusercontent.com/5707457/156351922-e069ed87-2178-4867-9af4-ba7ac4e59355.png)

```sh
❯ env|grep -i lv2 
LV2_PATH=/home/alf/.lv2:/usr/lib/lv2:/usr/local/lib/lv2

❯ locate geonkick
/usr/bin/geonkick
/usr/lib/lv2/geonkick.lv2
/usr/lib/lv2/geonkick.lv2/geonkick.ttl
/usr/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
/usr/lib/lv2/geonkick.lv2/manifest.ttl
/usr/share/applications/geonkick.desktop
/usr/share/doc/geonkick
/usr/share/doc/geonkick/README.md.gz
/usr/share/doc/geonkick/changelog.Debian.gz
/usr/share/doc/geonkick/copyright
/usr/share/icons/hicolor/128x128/apps/geonkick.png
/usr/share/icons/hicolor/16x16/apps/geonkick.png
/usr/share/icons/hicolor/22x22/apps/geonkick.png
/usr/share/icons/hicolor/24x24/apps/geonkick.png
/usr/share/icons/hicolor/32x32/apps/geonkick.png
/usr/share/icons/hicolor/48x48/apps/geonkick.png
/usr/share/icons/hicolor/64x64/apps/geonkick.png
/usr/share/icons/hicolor/scalable/apps/geonkick.svg
/usr/share/mime/application/x-geonkick-preset.xml
/usr/share/mime/packages/geonkick.xml
/var/lib/dpkg/info/geonkick.list
/var/lib/dpkg/info/geonkick.md5sums
```

![image](https://user-images.githubusercontent.com/5707457/156351806-ced0837c-e820-4b05-b0b9-688644ea1ab3.png)

**Comment by falkTX** [comment]
There is a check for mono or stereo output plugins in https://github.com/DISTRHO/Ildaeil/blob/main/plugins/Common/IldaeilUI.cpp#L660
multi-out plugins like geonkick that has 16 audio ports won't show up in ildaeil.

**Comment by fractalf** [comment]
ok. just out of curiousity, is this hard to implement so it will never be done, or is it just not planned or done yet? Could you not just "pick" the first 2 outputs out of the 16 :)

**Comment by falkTX** [comment]
removing the check for the only-2-outs would already do that
but not sure if that applies nicely to geonkick. at least on the lv2 version each output seems independent.

**Comment by fractalf** [comment]
Right, well some of this is above my comprehention, but I find it really weird why a plug like Geonkick should have 16 outputs...
The standalone seems to have one, that I must manually "split" to get a stereo signal

![image](https://user-images.githubusercontent.com/5707457/156946254-7b2bb841-db4e-4118-aec7-99f37ec183af.png)

**Comment by falkTX** [comment]
Latest geonkick includes an lv2 stereo version, so this then stops being an issue.
I am updating the kxstudio package for it right now.
